CREATE TABLE [dbo].[Sales]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	[ArticleNumber] VARCHAR(32) NOT NULL,
	[Price] MONEY NOT NULL,
	[DateCreated] DATETIME2 NOT NULL DEFAULT GETDATE()
)
